services:
  mysql:
    image: mysql:8.0
    container_name: invoice-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoice_db
      MYSQL_USER: invoice
      MYSQL_PASSWORD: invoice
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
